data:
  # Dossier contenant les tracés
  directory: './public/data/Cardio_Respi/Data_2016/savatier'
  channels:
    - name: 'CH1'
      description: 'spirométrie (amplitude ventilation)'
      id: 'SP'
      bounds: [-2, 2]
    - name: 'CH2'
      description: 'Pression artérielle, en mmHg'
      id: 'PA'
      bounds: [5, 300]
    - name: 'CH40'
      description: 'Fréquence ventilatoire, en ventilations/min'
      id: 'FV'
      bounds: [0, 50]
    - name: 'CH41'
      description: 'Fréquence cardiaque, en BPM'
      id: 'FC'
      bounds: [0, 300]
  # Prefixes des fichiers à collecter. Si vide, tout est collecté
  keys: []#['Sansinjection', 'Adrenaline', 'Acetylcholine']
  # Prefixe des fichiers correspondant à l'état repos
  stable_state: 'Sansinjection'

arduino:
  port: 'COM7'
  baudrate: 2000000
  poumon: 'CH40'
  coeur: 'CH41'

plotting:
  # name of the channel to plot
  channels: ['CH1', 'CH2']#, 'CH40', 'CH41']