data:
  cardiorespi:
      directory: './public/data/Cardio_Respi/Data_2016/savatier'
      # Prefixes des fichiers à collecter. Si vide, tout est collecte
      keys: []#['Sansinjection', 'Adrenaline', 'Acetylcholine']
      # Prefixe des fichiers correspondant à l'etat repos
      stable_state: 'Sansinjection'
      # Dossier contenant les tracés
      channels:
        - name: 'CH1'
          description: 'spirometrie (amplitude ventilation)'
          id: 'SP'
          bounds: [-2, 2]
        - name: 'CH2'
          description: 'Pression arterielle, en mmHg'
          id: 'PA'
          bounds: [5, 300]
        - name: 'CH40'
          description: 'Frequence ventilatoire, en ventilations/min'
          id: 'FV'
          bounds: [0, 50]
        - name: 'CH41'
          description: 'Frequence cardiaque, en BPM'
          id: 'FC'
          bounds: [0, 300]
      plotting: ['CH40', 'CH41','CH1', 'CH2']
      poumon: 'CH40'
      coeur: 'CH41'
      buzzer: None

  cardiorenale:
      directory: './public/data/Cardio_Renale/Bouvier'
      # Prefixes des fichiers à collecter. Si vide, tout est collecte
      keys: []#['Sansinjection', 'Adrenaline', 'Acetylcholine']
      # Prefixe des fichiers correspondant à l'etat repos
      stable_state: 'Sansinjection'
      channels:
        - name: 'Diurese'
          description: 'Diurèse (volume des urines émises)'
          id: 'D'
          bounds: [60, 110]
        - name: 'Blood Pressure'
          description: 'Pression arterielle, en mmHg'
          id: 'BP'
          bounds: [40, 100]
        - name: 'Heart Rate'
          description: 'Frequence cardiaque, en BPM'
          id: 'FC'
          bounds: [0, 300]
      plotting: ['Diurese', 'Blood Pressure','Heart Rate']
      buzzer: 'Diurese'
      poumon: None
      coeur: 'Heart Rate'

arduino:
  mock: True
  port: 'COM7'
  baudrate: 2000000